### ISSUE TITLE
Spades assembly being recongnized as Invalid meta/single genome type

### ISSUE THREAD

**Issue by yoyohashao** [hyattpd/Prodigal#10]
Prodigal V2.6.2: February, 2015 

Command line and error:

SEBASTIANs-MacBook-Pro:~ FLFLFLLF$ prodigal -i /Users/FLFLFLLF/spades_3rd_lf10sc_notmp/contigs.fna -o lf10spades_coords.gbk -a lf10proteins.faa -p anon

Invalid meta/single genome type specified.

The format of my assembly fasta file:
NODE_4604_length_1093_cov_92.9644_ID_9355

ATCGCTGTAGCATCTCCGCCCCAGGCGGAGTTTGGTGGGTTGCCGCACCCGAGCATCTTG
GCGCTGTGTCATCTACTGGGTGTCAATGAGGTCTACGCCGTCGGCGGTGCCCAGGCGATC
G

It's my first time to use Prodigal....I didn't see anything wrong with my fasta file...Thanks for you help

**Comment by tseemann** [comment]
@yoyohashao You used the command line `-p anon` but if I type `prodigal -h` that is an invalid option. It says `-p:  Select procedure (single or meta).  Default is single.`.

**Comment by hyattpd** [comment]
FASTA header lines should begin with ">".  I don't see one here.

Also, Torsten is correct.  "-p anon" is an upcoming option in 3.0.  From the wiki:

Anonymous Mode

To run Prodigal in anonymous mode, just add a '-p anon' option to the command line, i.e.

$ prodigal -i metagenome.fna -o coords.gbk -a proteins.faa -p anon
Prodigal 2.x: In older versions of Prodigal, this mode was known as metagenomic mode, and was invoked using the -p meta option. Prodigal 3.x will continue to support this syntax, although -p meta is considered deprecated. We chose to rename this mode to anonymous mode since this more accurately describes its function, which is not solely limited to metagenomic sequences.
