### ISSUE TITLE
meta mode and translation table 4

### ISSUE THREAD

**Issue by tseemann** [hyattpd/Prodigal#19]
Doug

Can you have a look at this Prodigal question/issue posted to Prokka?

https://github.com/tseemann/prokka/issues/112

**Comment by davidbur** [comment]
+1
When applying `-p meta` disregards `-g xx`.
I tried `-p meta -g 25` and stop codons were assigned for UGA codons.

Thanks.

**Comment by ShaiberAlon** [comment]
Hi,

Any plans on addressing this?

I run into a very similar problem to that @davidbur mentioned above:
I try to use `-p meta -g 25`, and while UGA is not assigned to stop codon, it is translated to tryptophan (translation table 4) instead of glycine (translation table 25). If I use `-p single -g 25` then UGA is translated to glycine properly.

Thank you!

**Comment by hyattpd** [comment]
This will be supported in the Go version (user will be able to specify which genetic codes of the pre-built models they want to use).

**Comment by ShaiberAlon** [comment]
Hi @hyattpd , thanks for following-up on this! What is the Go version?

**Comment by hyattpd** [comment]
New version that I am developing... I'll post more in the main README for Prodigal once it's closer to done.
