### ISSUE TITLE
Restrict start codons to AUG

### ISSUE THREAD

**Issue by sjackman** [hyattpd/Prodigal#22]
I'm using translation table 11 to annotate a plant plastid genome. Is it possible to limit the possible start codons to only AUG?

**Comment by hyattpd** [comment]
Translation table 1 only allows ATG, but otherwise works the same as 11.
So can just specify genetic code 1.

regards,
doug

**Comment by sjackman** [comment]
Thanks for your quick response, Doug. Because the plastid genome is so small (120 kbp) I've been using the metagenomics mode `-p meta` as I was concerned that there wasn't enough data for training. Enabling metagenomics mode also appears to force the translation table to 11. The option `-g 1` has no effect on the translation table used by Prodigal when metagenomics mode is enabled. Is it possible to use the options `-p meta -g 1` together?

**Comment by hyattpd** [comment]
120kb should be fine to just run with -g 1.

The whole "-p meta" + "-g X" is an issue that Torsten has brought up with Prokka, etc., and also here.  The way MetaProdigal works is it uses a series of preset training files (from genetic codes 11 and 4 only), and this is why there is no capability to specify a genetic code.  The idea is that if you're running with "-p meta", it's because you don't know what the genome is.

Now more and more people are using "-p meta" just because the sequence is small (this is not surprising, since I recommend doing this in the wiki), even though they know exactly what the sequence is (in terms of genetic code, etc.)  So maybe in a future version, I'll figure out a way to support this.  Probably I would not change how "-p meta" works, but would merely make Prodigal's normal mode handle small sequences seamlessly w/o the user needing to worry about it (so you could just run a 5kb sequence through normal mode with -g 1 and Prodigal would just handle it correctly).

**Comment by sjackman** [comment]
Cool. I'll try `-g 1`. Thanks for the explanation, Doug.
