### ISSUE TITLE
Handling broken backward compatility between 2.60 and 2.70

### ISSUE THREAD

**Issue by tseemann** [hyattpd/Prodigal#3]
Doug

Sean Jackman has alerted me to your git version of prodigal (aka 2.70) breaking backward compatibility of command line options with the long standing 2.60 version:
- https://github.com/Victorian-Bioinformatics-Consortium/prokka/issues/16

Prodigal is very popular (fast and reliable) and it is not customary to break interfaces for minor versions.

As I can see from your notes that most of this is in preparation for 3.00. Are you planning any official/stable releases for 2.70? 

Torsten

**Comment by hyattpd** [comment]
Hi,

Thanks for bringing the numbering to my attention.  I do intend to embrace
semantic versioning moving forward.

I wouldn't pay much attention to the version labels in my development
source commits.  The next release will be 3.0.0-something.  I planned 3 big
additions before 3.0, one of which is almost done.  Most likely I will
release these as 3.0.0-alpha.1 , 2, and 3, rather than waiting a year to
release.

Releasing as 3.0.0, 3.1.0, and 3.2.0 doesn't feel right either, since gene
predictions will change (which to me constitutes a major revision even if
options don't change from 3.0.0 to 3.x.0), and I don't really want to call
them 3.0.0, 4.0.0, and 5.0.0.

Regards,
Doug

**Comment by tseemann** [comment]
I've added a check in prokka requiring Prodigal >= 2.60 and < 2.70 to solve this problem from my end. Looking forward to the next release!
