### ISSUE TITLE
Use -p single or -p meta for metagenomic bins

### ISSUE THREAD

**Issue by SarahIsme** [hyattpd/Prodigal#57]
After the binning of assembled contigs file, I get a bin set. I want to make gene prediction on each bin.

However, I'm confused by the option `-p single or meta` when I add it to command. It seems right to use `-p single`, because each bin could be thought as draft genome. But on the other hand, each bin includes many contigs which were assembled from metagenomic reads, so it also seems right to to use `-p meta`. 

Which parameter should I use for each bin?

Thanks in advance!

**Comment by Ash1One** [comment]
Hello, @SarahIsme . I have the same question. 
I think
`-p single` should be uesd as each bin should be a draft single genome. 
`-p meta` option is used when the assembly of metagenome is the input of Prodigal as assembly file contain a lot of microbial genome fragment.
I don't know if my understanding is correct.

**Comment by tseemann** [comment]
I agree with @Ash1One - if you have binned contigs that are probably a MAG, then use `-p single`. The main problem is which genetic code to use... `-gc 11` is probably fine, but if it is a weird archaea or _Mycoplasma_ you will need `-gc 4` for example.

**Comment by hyattpd** [comment]
Although the wiki is bad in some sense, because it refers to a version/syntax that will never be made (since I'm now actively working on "radigal" in Go), it does go over all this.

You always want "-p single" when you know everything belongs to one genome, though, @tseemann is correct that you do need to know the genetic code.  (Future versions will auto-detect the genetic code, so this won't be necessary).  So, yes, "-p single" (the default, don't need to specify this) on binned contigs.

"-p meta" should be used on short sequences (when insufficient data exists to train on), and on any mixed samples (metagenomic assemblies, etc.)
